In [1]:
import pandas as pd

In [3]:
df= pd.read_csv(r"D:\All data\pima-indians-diabetes.csv")

In [5]:
df

      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [9]:
filename="D:\All data\pima-indians-diabetes.csv"
names=["pregnancy", "pals", 'pres ','test','mass''pedi','age','class']
df= pd.read_csv(filename,names= names)
df

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\ArtiR\AppData\Local\Temp\ipykernel_18396\1955868328.py:1: SyntaxWarning: invalid escape sequence '\A'
  filename="D:\All data\pima-indians-diabetes.csv"

        pregnancy  pals  pres   test  masspedi  age  class
6  148         72    35      0  33.6     0.627   50      1
1  85          66    29      0  26.6     0.351   31      0
8  183         64     0      0  23.3     0.672   32      1
1  89          66    23     94  28.1     0.167   21      0
0  137         40    35    168  43.1     2.288   33      1
...           ...   ...    ...   ...       ...  ...    ...
10 101         76    48    180  32.9     0.171   63      0
2  122         70    27      0  36.8     0.340   27      0
5  121         72    23    112  26.2     0.245   30      0
1  126         60     0      0  30.1     0.349   47      1
   93          70    31      0  30.4     0.315   23      0

[768 rows x 7 columns]

In [11]:
df.shape

(768, 7)

In [15]:
df.columns

Index(['pregnancy', 'pals', 'pres ', 'test', 'masspedi', 'age', 'class'], dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 768 entries, (6, 148) to (1, 93)
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pregnancy  768 non-null    int64
 1   pals       768 non-null    int64
 2   pres       768 non-null    int64
 3   test       768 non-null    float64
 4   masspedi   768 non-null    float64
 5   age        768 non-null    int64
 6   class      768 non-null    int64
dtypes: float64(2), int64(5)
memory usage: 50.1 KB

In [23]:
df.describe()

,pregnancy,pals,pres,test,masspedi,age,class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [25]:
df.isnull().sum()

pregnancy    0
pals         0
pres         0
test         0
masspedi     0
age          0
class        0
dtype: int64

In [27]:
df.isnull()

        pregnancy   pals  pres    test  masspedi    age  class
6  148      False  False  False  False     False  False  False
1  85       False  False  False  False     False  False  False
8  183      False  False  False  False     False  False  False
1  89       False  False  False  False     False  False  False
0  137      False  False  False  False     False  False  False
...           ...    ...    ...    ...       ...    ...    ...
10 101      False  False  False  False     False  False  False
2  122      False  False  False  False     False  False  False
5  121      False  False  False  False     False  False  False
1  126      False  False  False  False     False  False  False
   93       False  False  False  False     False  False  False

[768 rows x 7 columns]

In [33]:
df.dtypes

pregnancy      int64
pals           int64
pres           int64
test         float64
masspedi     float64
age            int64
class          int64
dtype: object

In [37]:
x= df.iloc[:,:-1]

x

        pregnancy  pals  pres   test  masspedi  age
6  148         72    35      0  33.6     0.627   50
1  85          66    29      0  26.6     0.351   31
8  183         64     0      0  23.3     0.672   32
1  89          66    23     94  28.1     0.167   21
0  137         40    35    168  43.1     2.288   33
...           ...   ...    ...   ...       ...  ...
10 101         76    48    180  32.9     0.171   63
2  122         70    27      0  36.8     0.340   27
5  121         72    23    112  26.2     0.245   30
1  126         60     0      0  30.1     0.349   47
   93          70    31      0  30.4     0.315   23

[768 rows x 6 columns]

In [43]:
y= df.iloc[:,-1]
y

6   148    1
1   85     0
8   183    1
1   89     0
0   137    1
          ..
10  101    0
2   122    0
5   121    0
1   126    1
    93     0
Name: class, Length: 768, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split

In [55]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state= 28)

In [57]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((614, 6), (154, 6), (614,), (154,))

In [65]:
from sklearn.neighbors import KNeighborsClassifier

In [97]:
knn= KNeighborsClassifier(n_neighbors=3)
knn. fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [99]:
#trainning accurcy
y_train_prd= knn.predict(x_train)

In [101]:
from sklearn.metrics import confusion_matrix,classification_report

In [103]:
confusion_matrix(y_train,y_train_prd)

array([[341,  56],
       [ 66, 151]], dtype=int64)

In [105]:
print(classification_report(y_train,y_train_prd))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       397
           1       0.73      0.70      0.71       217

    accuracy                           0.80       614
   macro avg       0.78      0.78      0.78       614
weighted avg       0.80      0.80      0.80       614

In [107]:
# test_accuracy
y_test_prd = knn.predict(x_test)

In [109]:
confusion_matrix(y_test,y_test_prd)

array([[74, 29],
       [27, 24]], dtype=int64)

In [95]:
print(classification_report(y_test,y_test_prd))

              precision    recall  f1-score   support

           0       0.73      0.79      0.76       103
           1       0.49      0.41      0.45        51

    accuracy                           0.66       154
   macro avg       0.61      0.60      0.60       154
weighted avg       0.65      0.66      0.65       154

In [ ]:
create a loop  for knn 
Acc vs  knn value