In [1]:
import pandas as pd

In [3]:
df= pd.read_csv(r"D:\All data\claimants.csv")

In [5]:
df

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [9]:
df.shape

(1340, 7)

In [22]:
df=df.drop("CASENUM",axis= 1)

In [24]:
df

      ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1335         1     0.0       1.0       0.0     NaN   0.576
1336         0     1.0       1.0       0.0    46.0   3.705
1337         1     1.0       1.0       0.0    39.0   0.099
1338         0     1.0       0.0       0.0     8.0   3.177
1339         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 6 columns]

In [32]:
x=df.drop("ATTORNEY", axis=1)

In [34]:
x

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1335     0.0       1.0       0.0     NaN   0.576
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1340 rows x 5 columns]

In [38]:
y=df["ATTORNEY"]
y

0       0
1       1
2       1
3       0
4       1
       ..
1335    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1340, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

In [50]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size= 0.2,random_state=123)

In [52]:
x_train.shape,  x_test.shape, y_train.shape , y_test.shape

((1072, 5), (268, 5), (1072,), (268,))

In [58]:
from sklearn.ensemble import GradientBoostingClassifier,RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators = 200 ,criterion = "entropy",max_depth= 4)

In [60]:
rf_model.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=4, n_estimators=200)

In [62]:
from sklearn.model_selection  import GridSearchCV

In [68]:
y_train_prd= rf_model.predict(x_train)
y_train_prd

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [88]:
print(Classification Rport( y_train,y_train_prd))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2447868342.py, line 1)

In [72]:
from sklearn.metrics import roc_curve, roc_auc_score

In [80]:
fpr,tpr,threshold= roc_curve(y,rf_model.predict_proba(x)[:,1])
auc= roc_auc_score(y_train,y_train_prd)
print(auc)

0.7462243120863811

In [82]:
import matplotlib.pypplot as plt
plt.plot(fpr,tpr,color= "red".label = "rfmodel(area=0.2f)" %auc)
plt.polt[0,1], [0,1],'k__'
plt.x_label("False posititive rate or [1= True negative rate]")
plt.y_label("True Positive Rate")

SyntaxError: invalid syntax (709652993.py, line 2)